dist: bionic
language: node_js

# Support Active LTS versions of Node.js
node_js:
  - '10'
  - '12'

install:
  - npm install

script:
  - npm run pkgverchk
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script:
    # Ensure tag number matches the one in package.json
    - test v"$(jq -r .version package.json)" = "$TRAVIS_TAG"
    # Only deploy on ONE Node version
    - test "$TRAVIS_NODE_VERSION" = "12"
    - npm publish
  on:
    tags: true
    repo: dashevo/dark-gravity-wave-js
